version: '3'
services:
    wordpress:
        depends_on:
            - db
        privileged: true
        build:
            context: ../
            dockerfile: wp.dockerfile

        # required for mounting bindfs
        cap_add:
            - SYS_ADMIN
        devices:
            - /dev/fuse
        # required on certain cloud hosts
        security_opt:
            - apparmor:unconfined

        ports:
            - 8080:80
            - 443:443
        volumes:
            - ./data:/data
            - ./themes/plugin-builder:/app/wp-content/themes/plugin-builder
            - ./wp-tests-config.php:/app/wp-tests-config.php
            - ./scripts:/docker-entrypoint-initwp.d
        environment:
            WP_TESTS_DOMAIN: example.org
            WP_DEBUG: true
            WP_DEBUG_LOG: true
            DB_NAME: wordpress
            DB_USER: root
            DB_PASS: root
            PLUGINS: >-
                co-authors-plus
            EXTRA_PHP: >-
                define('WP_MEMORY_LIMIT', '256M');

    db:
        image: mariadb:10 # or mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 22222:80

volumes:
    data:
